

ALTER TABLE branch ADD PRIMARY KEY (BNUM);

ALTER TABLE card  ADD PRIMARY KEY (SERIAL_NUM);

ALTER TABLE complaints  ADD PRIMARY KEY (CODE);

ALTER TABLE customer  ADD PRIMARY KEY (ID);

ALTER TABLE customer_offer  ADD PRIMARY KEY (ID);

ALTER TABLE customer_service  ADD PRIMARY KEY (ID);

ALTER TABLE department  ADD PRIMARY KEY (DNUM);

ALTER TABLE employee  ADD PRIMARY KEY (SSN);

ALTER TABLE faq  ADD PRIMARY KEY (ID);

ALTER TABLE offer  ADD PRIMARY KEY (ID);

ALTER TABLE plan  ADD PRIMARY KEY (ID);

ALTER TABLE service  ADD PRIMARY KEY (SERVICE_ID);




SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE card  ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (ID);

ALTER TABLE complaints  ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (ID);
ALTER TABLE complaints  ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee (SSN);

ALTER TABLE customer  ADD FOREIGN KEY (PLAN_ID) REFERENCES plan (ID);

ALTER TABLE customer_offer  ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (ID);
ALTER TABLE customer_offer  ADD FOREIGN KEY (OFFER_ID) REFERENCES offer (ID);

ALTER TABLE customer_service  ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (ID);
ALTER TABLE customer_service  ADD FOREIGN KEY (SERVICE_ID) REFERENCES service (SERVICE_ID);

ALTER TABLE department  ADD FOREIGN KEY (MGR_SSN) REFERENCES employee (SSN);

ALTER TABLE employee  ADD FOREIGN KEY (DEPT_NUM) REFERENCES department (DNUM);
ALTER TABLE employee  ADD FOREIGN KEY (BRANCH) REFERENCES branch (BNUM);

ALTER TABLE faq  ADD FOREIGN KEY (SSN) REFERENCES employee (SSN);


ALTER TABLE complaints MODIFY DATE DATE;

ALTER TABLE offer MODIFY EXPIRE_DATE DATE;

ALTER TABLE faq  MODIFY DATE DATE;

